// TreatmentPlan.js
import mongoose from "mongoose";

/**
 * TreatmentPlan Schema
 * Stores validated, structured 15-day acne treatment plans
 * Generated by AI and strictly validated
 */
const treatmentPlanSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true
    },

    predictionSessionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "PredictionSession",
      required: true,
      index: true
    },

    severity: {
      type: String,
      required: true,
      enum: ["mild", "moderate", "severe"]
    },

    planType: {
      type: String,
      enum: ["free_15day", "premium_30day"],
      default: "free_15day"
    },

    generatedBy: {
      type: String,
      default: "grok_api",
      enum: ["grok_api", "manual"]
    },

    /**
     * Validated treatment plan structure
     * Must follow strict schema:
     * {
     *   days: [
     *     {
     *       dayNumber: 1-15,
     *       morning: string,
     *       afternoon: string,
     *       evening: string,
     *       lifestyleTips: string
     *     }
     *   ]
     * }
     */
    treatmentPlan: {
      type: {
        days: [
          {
            dayNumber: {
              type: Number,
              required: true,
              min: 1,
              max: 15
            },
            morning: {
              type: String,
              required: true
            },
            afternoon: {
              type: String,
              required: true
            },
            evening: {
              type: String,
              required: true
            },
            lifestyleTips: {
              type: String,
              required: true
            },
            _id: false
          }
        ]
      },
      required: true
    },

    status: {
      type: String,
      enum: ["active", "completed", "modified"],
      default: "active",
      index: true
    },

    /**
     * Metadata about plan generation
     * Useful for debugging and monitoring
     */
    generationMetadata: {
      // Groq API may provide usage info
      groqModel: {
        type: String,
        default: "llama-3.3-70b-versatile"
      },
      // Number of retries used
      retriesUsed: {
        type: Number,
        default: 0,
        min: 0,
        max: 1
      },
      // Time taken to generate (ms)
      generationTimeMs: {
        type: Number,
        default: 0
      },
      // Validation timestamp
      validatedAt: {
        type: Date,
        default: Date.now
      }
    },

    /**
     * Only one active plan per session
     * Compound index ensures uniqueness
     */
    isActive: {
      type: Boolean,
      default: true,
      index: true
    }
  },
  { 
    timestamps: true,
    indexes: [
      { userId: 1, status: 1 },
      { predictionSessionId: 1, isActive: 1 }
    ]
  }
);

// Compound unique index: only one active plan per session
treatmentPlanSchema.index(
  { predictionSessionId: 1, isActive: 1 },
  { unique: true, sparse: true }
);

export default mongoose.model("TreatmentPlan", treatmentPlanSchema);

